### ISSUE TITLE
What's my API url...

### ISSUE THREAD

**Issue by shealavington** [directus/cloud-beta#10]
I see a button at the bottom of my dashboard showing me the API reference, however if I wanted to use my API and play with the endpoints, there's no visual asfar as I can see to show me what my API url is. (Though yes I can copy it from the login screen after clicking the button, that's not user friendly)

![image](https://user-images.githubusercontent.com/16869302/54957713-796f7580-4f4b-11e9-829d-af7d38b70ad5.png)

**Comment by benhaynes** [comment]
I agree. Let's add a new section to this modal/pane:

1. Launch Directus — As is
2. API URL — Label with readonly input below it for selecting the API URL, and a text link below that to open up a public access point (maybe `/server/ping`?)
3. API Access Tokens — As is
