### ISSUE TITLE
Optimization: Storage

### ISSUE THREAD

**Issue by shealavington** [directus/cloud-beta#11]
So that Directus doesn't have to pay for un-nessessary storage, it may be worth, upon deletion of a project within the dashboard, also removing all files from AWS.

I've deleted my project, but there seems to be a file still available, I'm not sure if this is a cache or not, but just so you're aware, I'm writing this haha.

Remaining file: https://directus.media/dcNsHFEWCD2/z1bs5mqv7w421.jpg

**Comment by benhaynes** [comment]
I'm going to label this as a bug since it _definitely_ needs to delete all files when removing a project.
