### ISSUE TITLE
User-Flow confusion

### ISSUE THREAD

**Issue by shealavington** [directus/cloud-beta#4]
Went to delete a team, it wasn't immediately obvious I had to interact with the input above the big red button...

![image](https://user-images.githubusercontent.com/16869302/54955083-3958c480-4f44-11e9-9708-45efad44cd67.png)

Perhaps it should act like the account deletion and have the input next to the button
![image](https://user-images.githubusercontent.com/16869302/54955126-5d1c0a80-4f44-11e9-9f96-f03e6d1fbf69.png)

**Comment by benhaynes** [comment]
Yeah, we should use the "side-by-side layout for both. And we should update the input placeholder to:

`Type "Captains" to confirm...`

Lastly, let's make the "This action is perm..." text full-width so it flows under both buttons.
