### ISSUE TITLE
Project Creation: Emailed details

### ISSUE THREAD

**Issue by shealavington** [directus/cloud-beta#7]
Rijk rightfully pointed out that my project access information had been emailed to me, this wasn't clear to me, I just followed the visual clues, nothing told me I'd receive an email with my access information so I didn't think to check there, may need a visual clue to say "Congratulations on setting up a new project, your initial access information has been emailed to you, you can change this after logging in".

"Created Team"
"Created Project"
"Clicked Launch Project"
"Errm what now.."

**Comment by benhaynes** [comment]
Good point! We can use the existing notifications system for this, but we'd need them to stay on the screen until clicked (so we know the user saw it), or we can create a custom modal/alert that is bigger, more styled, and has more info.

Preference @shealavington @rijkvanzanten ?

**Comment by shealavington** [comment]
I think, as the notifications disappear quickly, they're not really a solid option, a modal would work, but even some small descriptive text would work too `If this is your first time setting up a project, your access information will be emailed to you`

Either a small description or modal :thinking:

**Comment by rijkvanzanten** [comment]
Yeah I think a little note right before the "Create project button" on that modal should already cover this.

"We'll email you the login details once the project is created."

We could even add a "admin password" field to that same project modal setup, that way we don't have to generate and email a random password!

**Comment by benhaynes** [comment]
Oooh, I like the idea of letting them choose their admin password. So, three changes:

1. Add info box to bottom of Create Project modal (same as account>invites): `Project and admin details will be emailed to all team members.`
2. Update notification:
```
*Project Created*
Details have been emailed to team members
```
3. Add input that allows setting initial admin password.

**Comment by rijkvanzanten** [comment]
> Details have been emailed to team members

Right now the email will only be send to the team owner. Do we want to send that email to all members of the team?

**Comment by benhaynes** [comment]
Hmm, owner seems like enough for now... we can expand this in the future when we create more granular roles.
