### ISSUE TITLE
Project Card: Not always clickable

### ISSUE THREAD

**Issue by shealavington** [directus/cloud-beta#8]
I load up my dashboard, I go to view my project informaiton, I click on my project multiple times, nothing happens, no network requests, no modals showing, give it a refresh, still nothing. 

The way to get it to work, is to interact with something valid, for example, clicking the project does nothing, but if I click `create team`, cancel that, and then click the project, it seems to work. 

I thought it was a non-issue but it's become increasingly annoying every time I went back haha.

![image](https://user-images.githubusercontent.com/16869302/54957317-4a0c3900-4f4a-11e9-87e8-10a0d3e4b590.png)

**Comment by benhaynes** [comment]
Weird... that's no good! We'll take a look.
